# Generated by Django 5.2.3 on 2025-06-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='admission_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
