# Generated by Django 5.2.3 on 2025-06-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
