# Generated by Django 5.2.3 on 2025-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_patientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
