# Generated by Django 5.2.3 on 2025-06-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_patient_discharge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('General', 'General'), ('ICU', 'ICU'), ('Private', 'Private')], max_length=20),
        ),
    ]
